# Define the frontend production pipelines.
include:
  - component: $CI_SERVER_FQDN/cdso/cdso/review@main
    inputs:
      name: greenpages-frontend
      pipeline_type: application-container
      cdso_config_path: .gitlab/expedition-0/prod/cdso_config.prod.yml

  - component: $CI_SERVER_FQDN/ai2c/caravan/pipelines/deliver@main
    inputs:
      name: greenpages-frontend
      pipeline_type: container
      expedition: 0
      environment: prod
      cdso_config_path: .gitlab/expedition-0/prod/cdso_config.prod.yml
