-- Creates clean staging tables for the WD83AA manual CSV load.
-- This file does not touch live Green Pages tables.

CREATE SCHEMA IF NOT EXISTS staging;

DROP TABLE IF EXISTS staging.greenpages_people_wd83aa;
DROP TABLE IF EXISTS staging.greenpages_billets_wd83aa;
DROP TABLE IF EXISTS staging.greenpages_billet_occupants_wd83aa;

CREATE TABLE staging.greenpages_people_wd83aa (
    person_id TEXT,
    dod_id TEXT,
    display_name TEXT,
    normalized_display_name TEXT,
    rank TEXT,
    grade TEXT,
    source_grade_normalized TEXT,
    component TEXT,
    work_email TEXT,
    phone TEXT,
    duty_phone TEXT,
    work_phone TEXT,
    office_symbol TEXT,
    is_current TEXT,
    source_lineage TEXT
);

CREATE TABLE staging.greenpages_billets_wd83aa (
    prototype_billet_key TEXT,
    auth_line_key TEXT,
    source_fms_pers_auth_pk TEXT,
    aos_position_id TEXT,
    uic TEXT,
    organization_name TEXT,
    component TEXT,
    unit_type TEXT,
    macom_text TEXT,
    aos_unit_id TEXT,
    aos_unit_type_clean TEXT,
    positions_admin_parent_uic TEXT,
    positions_dircon_parent_uic TEXT,
    positions_taabase_parent_uic TEXT,
    section_name TEXT,
    normalized_section_name TEXT,
    section_code TEXT,
    section_display_name TEXT,
    subsection_name TEXT,
    sub_unit TEXT,
    position_number TEXT,
    billet_title TEXT,
    normalized_billet_title TEXT,
    grade_code TEXT,
    source_grade_raw TEXT,
    rank_group TEXT,
    mpc_short TEXT,
    branch_code TEXT,
    posco TEXT,
    aos_posco TEXT,
    specialty_code TEXT,
    mos_code TEXT,
    aoc_code TEXT,
    aos_mos_code_raw TEXT,
    aos_code_description TEXT,
    paragraph_number TEXT,
    line_number TEXT,
    line_number_int TEXT,
    authorized_strength TEXT,
    authorized_strength_int TEXT,
    required_strength TEXT,
    identity_code TEXT,
    source_prmk1 TEXT,
    fiscal_year TEXT,
    change_number TEXT,
    unit_effective_date TEXT,
    aos_effdt TEXT,
    aos_effdt_to TEXT,
    duty_location TEXT,
    state_code TEXT,
    occupancy_status TEXT,
    is_current TEXT,
    aos_join_status TEXT,
    source_lineage TEXT
);

CREATE TABLE staging.greenpages_billet_occupants_wd83aa (
    billet_occupant_source_key TEXT,
    prototype_billet_key TEXT,
    position_number TEXT,
    auth_line_key TEXT,
    current_unit_auth_line_key TEXT,
    uic TEXT,
    paragraph_number TEXT,
    line_number TEXT,
    cu_authorization_document_paragraph_number TEXT,
    cu_authorization_document_line_number TEXT,
    section_name TEXT,
    section_display_name TEXT,
    billet_title TEXT,
    grade_code TEXT,
    rank_group TEXT,
    branch_code TEXT,
    mos_code TEXT,
    aoc_code TEXT,
    dod_id TEXT,
    person_id TEXT,
    person_rank TEXT,
    person_display_name TEXT,
    person_grade TEXT,
    person_component TEXT,
    person_work_email TEXT,
    person_work_phone TEXT,
    person_phone TEXT,
    person_duty_phone TEXT,
    person_office_symbol TEXT,
    is_primary TEXT,
    assignment_status TEXT,
    source_system TEXT,
    effective_date TEXT,
    source_assignment_status TEXT,
    source_current_assignment_indicator TEXT,
    source_position_fmid TEXT,
    positions_posco TEXT,
    overstrength_designation_code TEXT,
    source_designation_of_duties_performed TEXT,
    source_duty_title TEXT,
    is_current TEXT,
    source_lineage TEXT
);

