# Backend development deployment configuration.
organization: expedition-0
security_group: ai2c
deployment_level: DEVELOPMENT

greenpages-backend:
  project_type: container
  dockerfile_folder: backend
  container_lifespan: PERSISTENT
  connection_context: INTERNAL
