# ~/greenpages/app/.gitlab/expedition-0/dev/cdso_config.dev.yml
organization: expedition-0
security_group: ai2c
deployment_level: DEVELOPMENT

greenpages-backend:
  project_type: container
  dockerfile_folder: backend
  container_lifespan: PERSISTENT
  connection_context: INTERNAL

greenpages-frontend:
  project_type: container
  dockerfile_folder: frontend
  container_lifespan: PERSISTENT
